name: CI Job

on:
  push:
  pull_request:
    branches:
      - main

#These are jobs, adding a test to see
jobs:
  job1:
    name: Checkout SCM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
  job2:
    name: Unit test
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: echo "Will run unit test"

  job3:
    name: Sonar Analysis
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: echo " run sonar analysis"
  
  job4:
    name: build and publish
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Build Package
        run: echo "Build the required package"
      - name: Publish to artifactory
        run: echo "Publish to artifacory"

